import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "sonner";
import { SettingProvider } from "@/context/SettingContext";
import Navbar from "@/components/Shared/Navbar/Navbar";
import Footer from "@/components/Shared/Footer/Footer";

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Pen Packaging",
	description: "Generated by Pen Packaging",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html data-arp="" lang="en">
			<body
				data-new-gr-c-s-check-loaded="14.1243.0"
				data-gr-ext-installed=""
				className={` ${geistMono.variable} antialiased`}>
				<UserProvider>
					<SettingProvider>
						<Navbar />
						<Toaster position="top-right" />
						<div className="bg-white text-black">{children}</div>
						<Footer />
					</SettingProvider>
				</UserProvider>
			</body>
		</html>
	);
}
